addons:
  code_climate:
    repo_token: e438cb2f24b677f5638441a8f31d294e34afe3fb5a5b5ec9b2d13d5d1fdf4d12

install: bundle install --jobs 3 --retry 3

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head

script: bundle exec rspec
